spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: myThirdExchange
    queue: myThirdQueue
    routingkey: myThirdRoutingKey

server:
  port: 8080